---
title: "About"
format: html
editor: visual
---

This project was developed by **\[Team Viz Wizards\]** For [INFO 526 - Data Analysis & Visualization](https://datavizaz.org/) at the University of Arizona, taught by Dr. Greg Chism. The team is comprised of the following team members.

-   Team member 1: Jasdeep Singh Jhajj, is a 1st year graduate student in the Data Science program with the School of Information.

-   Team member 2: Agastya Deshraju, is a 1st year graduate student in the Data Science program with the School of Information.

-   Team member 3: Gillian McGinnis, is a 1st year graduate student in the Information Science - Machine Learning program with the School of Information.

-   Team member 4: Tanya Evita George, is a 1st year graduate student in the Data Science program with the School of Information.

-   Team member 5: Nick Ferrante, is a 1st year graduate student in the Data Science program with the School of Information.

-   Team member 6: Jeremiah Gaiser, is a PhD student in a computational pharmaceutical lab, formally with the School of Information.

-   Team member 7: Mrunal Jadhav, is a 2nd year graduate student in the Information Science program with the School of Information.
